# Generated by Django 4.2.27 on 2026-01-24 21:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlareUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("civilian", "Civilian"),
                            ("rescuer", "Professional Rescuer"),
                            ("admin", "Administrator"),
                        ],
                        default="civilian",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_verified_rescuer", models.BooleanField(default=False)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="flare_users",
                        related_query_name="flare_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="flare_users",
                        related_query_name="flare_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flare User",
                "verbose_name_plural": "Flare Users",
                "db_table": "flare_users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_memberships",
            },
        ),
        migrations.CreateModel(
            name="PrivateGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to="api.flareuser",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="private_groups",
                        through="api.GroupMembership",
                        to="api.flareuser",
                    ),
                ),
            ],
            options={
                "db_table": "private_groups",
            },
        ),
        migrations.CreateModel(
            name="SOSBeacon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("public", "Public Emergency"),
                            ("professional", "Professional Rescue"),
                            ("private", "Private Group"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rescued", "Rescued"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("bluetooth", "Bluetooth LE"),
                            ("wifi", "WiFi Direct"),
                            ("uwb", "Ultra-Wideband"),
                        ],
                        default="bluetooth",
                        max_length=20,
                    ),
                ),
                ("battery_level", models.IntegerField(default=100)),
                ("last_known_latitude", models.FloatField(blank=True, null=True)),
                ("last_known_longitude", models.FloatField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "emergency_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "private_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beacons",
                        to="api.privategroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_beacons",
                        to="api.flareuser",
                    ),
                ),
            ],
            options={
                "db_table": "sos_beacons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RescueSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rescuer_device_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescue_sessions",
                        to="api.sosbeacon",
                    ),
                ),
                (
                    "rescuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescue_sessions",
                        to="api.flareuser",
                    ),
                ),
            ],
            options={
                "db_table": "rescue_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="HeatMapData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grid_x", models.IntegerField()),
                ("grid_y", models.IntegerField()),
                ("signal_strength", models.IntegerField()),
                (
                    "cell_status",
                    models.CharField(
                        choices=[
                            ("clear", "Clear Path"),
                            ("obstacle", "Obstacle Detected"),
                            ("unstable", "Unstable Signal"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rescue_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_map_data",
                        to="api.rescuesession",
                    ),
                ),
            ],
            options={
                "db_table": "heat_map_data",
            },
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.privategroup"
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.flareuser"
            ),
        ),
        migrations.CreateModel(
            name="EmergencyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("earthquake", "Earthquake"),
                            ("flood", "Flood"),
                            ("fire", "Fire"),
                            ("collapse", "Building Collapse"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("center_latitude", models.FloatField(blank=True, null=True)),
                ("center_longitude", models.FloatField(blank=True, null=True)),
                ("radius_km", models.FloatField(default=10.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beacons",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="api.sosbeacon"
                    ),
                ),
            ],
            options={
                "db_table": "emergency_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BeaconDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rescuer_device_id", models.CharField(max_length=255)),
                ("rssi", models.IntegerField()),
                ("estimated_distance", models.FloatField()),
                ("signal_type", models.CharField(default="bluetooth", max_length=20)),
                ("rescuer_latitude", models.FloatField(blank=True, null=True)),
                ("rescuer_longitude", models.FloatField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.sosbeacon",
                    ),
                ),
                (
                    "rescuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.flareuser",
                    ),
                ),
            ],
            options={
                "db_table": "beacon_detections",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sosbeacon",
            index=models.Index(
                fields=["status", "mode"], name="sos_beacons_status_a1b654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosbeacon",
            index=models.Index(
                fields=["device_id"], name="sos_beacons_device__215733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosbeacon",
            index=models.Index(
                fields=["created_at"], name="sos_beacons_created_a20baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatmapdata",
            index=models.Index(
                fields=["rescue_session", "grid_x", "grid_y"],
                name="heat_map_da_rescue__eeccdf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="heatmapdata",
            unique_together={("rescue_session", "grid_x", "grid_y")},
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="beacondetection",
            index=models.Index(
                fields=["beacon", "detected_at"], name="beacon_dete_beacon__704179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beacondetection",
            index=models.Index(
                fields=["rescuer_device_id"], name="beacon_dete_rescuer_159bb8_idx"
            ),
        ),
    ]
